### ISSUE TITLE
Keep getting an error

### ISSUE THREAD

**Issue by Zemyoro** [fwcd/swift-discord#8]
I currently have Swift 5.4.2.
Ubuntu Linux 20.04

Using this template:
[here](https://github.com/nuclearace/SwiftBot)

I either added // swift-tools-version:5.4.0 or // swift-tools-version:5.4.0 but still got similar errors.
I changed the .target things to .executableTarget for 5.4.0 but I keep getting the error from below.

error: the manifest is missing a Swift tools version specification; consider prepending to the manifest '// swift-tools-version:5.4.0' to specify the current Swift toolchain version as the lowest Swift version supported by the project; if such a specification already exists, consider moving it to the top of the manifest, or prepending it with '//' to help Swift Package Manager find it

**Comment by fwcd** [comment]
Please see the [snippet](https://github.com/fwcd/swift-discord/blob/main/Snippets/PingPongBot.swift) for an up-to-date example. I'll close this as outdated.
